config/routes.rb
Concertx::Application.routes.draw do

  resources :events

  devise_for :users
  
  resources :users do
    resources :followers
  end

  root to: "events#index"

  get 'feed', to: 'events#list', as: :feed
  get 'followed', to: 'events#followed', as: :followed

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  paginates_per 6
  attr_accessible :soundcloud_artist_id, :soundcloud_artist_name, :soundcloud_track_name,
                  :soundcloud_track_id, :date, :description, :price, :time_duration,
                  :image
  validates_presence_of :soundcloud_artist_name, :description, :time_duration, :date
  validates :price, numericality: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x80>" }
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :follower_id, :user_id
  validates_uniqueness_of :user_id, scope: :follower_id
  belongs_to :user
  belongs_to :follower, class_name: "User"

  scope :following, lambda {|user_id| where(user_id: user_id) }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :events
  has_many :followers, class_name: 'Follower', foreign_key: 'follower_id'
  has_many :following, class_name: 'Follower', foreign_key: 'user_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :update, :edit, :list]

  def index
    @events = Event.order(:date).page params[:page]
  end

  def list
    users = []
    User.find(current_user.id).followers.each do |follower|
      users.push(follower.user.id)
    end
    @events = Event.where(user_id: users).order(:date).page params[:page]
  end

  def followed
    @users = User.find(current_user.id).followers
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])

    @event.user = current_user

    if @event.save
      UserMailer.new_event(@event, current_user).deliver
      redirect_to events_path, :notice => "Your event was created successfully."
    else
      flash[:error] = "There were some errors creating your event."
      render action: "new"
    end 
  end

  def update
    @event = Event.find(params[:id])
  
    if @event.update_attributes(params[:event])
      flash[:notice] = 'Your event was edited successfully'
      redirect_to action: 'show', id: @event
    else
      flash[:error] = "There were some errors editing your event"
      render action: 'edit'
    end
  end

  def delete
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def new
    @follower = Follower.new

    @follower.user_id = params[:user_id]
    @follower.follower_id = current_user.id
    @user = User.find(params[:user_id])

    @follower.save
    respond_to do |format|
      format.js { render 'button' }
    end
  end

  def destroy
    @follower = Follower.where(user_id: params[:user_id], follower_id: current_user.id).first
    @user = User.find(params[:user_id])
    if @follower.destroy
      respond_to do |format|
        format.js { render 'button' }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/events/_event.html.erb
<li class="media">
  <div class="pull-left">
    <%= image_tag event.image.url(:thumb), class: 'img-polaroid' if !event.image_file_name.nil? %>
  </div>
  <div class="media-body">
    <h3 class="media-heading">
      <%= link_to event.soundcloud_artist_name, event %> <small>(<%= event.date %> | On <%= distance_of_time_in_words_to_now(event.date, true) %>)</small>
    </h3>
    <div class="event-meta">
      <%= event.time_duration %> | <%= event.user.name %> 
      <span class="action-<%= event.user_id %>"><%= render partial: 'followers/button', locals: {user: event.user} %></span>
    </div>
  </div>
</li>

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: {class: 'form-horizontal', multipart: true}) do |f| %>
  <%= f.input :soundcloud_artist_name, as: :string, input_html: { style: 'width: 100%' } %>
  <%= f.input :soundcloud_track_id, collection: [@event.soundcloud_track_id], :prompt => "Select the track", input_html: { style: 'width: 100%' } %>
  <%= f.input :date, as: :string %>
  <%= f.input :price %>
  <%= f.input :time_duration %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, input_html: { style: 'width: 100%;height:200px' } %>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-large' %>
  </div>
  <%= f.input :soundcloud_artist_id, as: :hidden %>
<% end %>

app/views/events/_player.html.erb
<% require "soundcloud" %>
<% client = Soundcloud.new(client_id: 'f6f238c72b4d7e0b65c235c2590416c6') %>
<% embed_info = client.get('/oembed', url: @event.soundcloud_track_id) %>
<%= embed_info['html'].html_safe %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<hr>
<%= render 'form' %>

app/views/events/followed.html.erb
<h1>Followed Users</h1>
<% if @users.empty? %>

  <div class="well" style="text-align: center">
    <h2>You haven't followed any user...</h2>
  </div>

<% else %>
  <ul id="events-list" class="media-list">
  <% @users.each do |follower| %>
    <li class="media-content">
      <%= follower.user.name %>
      <span class="action-<%= follower.user.id %>"><%= render partial: 'followers/button', locals: {user: follower.user} %></span>
    </li>
  <% end %>
  </ul>
  
<% end %>

app/views/events/index.html.erb
<% if @events.empty? %>

  <div class="well" style="text-align: center">
    <h2>No events were found...</h2>
    <%= link_to 'Crete a new event', new_event_path %>
  </div>

<% else %>
  <ul id="events-list" class="media-list">
  <% @events.each do |event| %>
    <%= render partial: 'event', locals: {event: event} %>
  <% end %>
  </ul>

  <%= paginate @events %>
  
<% end %>

app/views/events/list.html.erb
<h1>Events from my followed users</h1>
<% if @events.empty? %>

  <div class="well" style="text-align: center">
    <h2>No events were found...</h2>
  </div>

<% else %>
  <ul id="events-list" class="media-list">
  <% @events.each do |event| %>
    <%= render partial: 'event', locals: {event: event} %>
  <% end %>
  </ul>

  <%= paginate @events %>
  
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
<hr>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="pull-right" style="text-align: center">
  <% if user_signed_in? and @event.user == current_user %>
  <%= link_to 'Edit Event', edit_event_path(@event), html_options = {class: 'btn btn-primary'}%>
  <% end %>
</div>

<h1 class="event-artist"><%= @event.soundcloud_artist_name %></h1>
<div class="row">
  <div class="span3">
    <b>Date</b>: <%= @event.date %>
  </div>
  <div class="span2">
    <b>Price</b>: $ <%= (@event.price > 0) ? @event.price : 'FREE!' %>
  </div>
  <div class="span3">
    <b>Time/Duration</b>: <%= @event.time_duration %>
  </div>
  <div class="span4">
    <b>Created by: </b>: <%= @event.user.name %> <span class="action-<%= @event.user_id %>"><%= render partial: 'followers/button', locals: {user: @event.user} %></span>
  </div>
</div>
<hr>
<div class="media">

  <% if !@event.image_file_name.nil? %>
    <div class="pull-left event-image">
      <%= image_tag @event.image.url(:medium), class: 'img-polaroid'  %>
    </div>
  <% end %>

  <div class="media-body">
    <p><%= simple_format(@event.description) %></p>
  </div>
</div>

<% if !@event.soundcloud_track_id.empty? %>
  <hr>
  <%= render 'player' %>
<% end %>

app/views/followers/_button.html.erb
<% if user_signed_in? %>
  <% follow = current_user.followers.following(user.id).first %>
  <% if follow %>
    <%= link_to 'Unfollow', user_follower_path(user, follow), remote: true, method: :delete, class: 'btn btn-mini' %>
  <% else %>
    <%= link_to 'Follow!', new_user_follower_path(user), remote: true, class: 'btn btn-mini btn-success' %>
  <% end %>
<% end %>

app/views/followers/button.js.erb
$('.action-<%= @follower.user_id %>').html('<%= j render partial: "followers/button", locals: {user: @user} %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concertx!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://connect.soundcloud.com/sdk.js"></script>
  <script type="text/javascript">
  SC.initialize({
    client_id: 'f6f238c72b4d7e0b65c235c2590416c6'
  });
  </script>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">Concertx!</a>
        <ul class="nav">
          <li><%= link_to 'All Events', root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "My Feed", feed_path %></li>
            <li><%= link_to "Followed Users", followed_path %></li>
            <li><%= link_to "New Event", new_event_path %></li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
         
    <%= yield %>
  </div>

  <br><br>
</body>
</html>